### ISSUE TITLE
csparc2star.py. bug- micrograph column is not generated when output file name is not explicitly given

### ISSUE THREAD

**Issue by mvorlander** [asarnow/pyem#100]
Hi there,

first of all, many thanks for maintaining this package! 

I have noticed that when you run csparc2star.py without explicitly giving it the name for  the output file, the output lacks the column for the micrographs. However this works just fine when you give it an output argument. 

so 

csparc2star.py particles.cs passthrough.cs 

does not work, while 

csparc2star.py particles.cs passthrough.cs  output.star 

works fine.  

Cheers,
Matthias

**Comment by asarnow** [comment]
Hi Matthias,
The last argument is the output file. The micrograph names are missing because they are in the passthrough file, which is not read if you run `csparc2star.py particles.cs passthrough.cs` because passthrough.cs is the output file. It would overwrite the file that's there, if it could, so be careful.

**Comment by mvorlander** [comment]
I see! Thanks for the explanation. Csparc2Star.py does not override the passthrough file, instead it generates an output file "passthrough.star ". That's where the confusion came friom, because it looked like everything works. Maybe this could be made clearer (perhaps print in the terminal when no passthrough file was supplied, only generating particle.stat file?).

Anyhow, thanks again for  your work, it really helps the community!

Cheers,
Matthias

**Comment by asarnow** [comment]
I have warnings if certain information, like defocus values or alignments, are missing, but the .cs files are all the same internally so pyem doesn't know which one is the main file. Indeed, sometimes you actually want to give them in a different order, because the first file determines which rows/particles are kept while filling in available information from any subsequent files.

I forgot that it always changes the output file to .star, so at least it won't overwrite your .cs file! I could have it print a warning if that file exists already perhaps.
