### ISSUE TITLE
New `csparc2star` default for `--inverty` breaks existing workflows

### ISSUE THREAD

**Issue by brisvag** [asarnow/pyem#101]
A collague came to me with a suddenly broken workflow; it turned out that sbgrid recently updated the pyem version, which now has `--inverty` on by default when running `csparc2star.py`.

Was this change intentional, and if so why? It seems that data from cryosparc is still coming out with uninverted `y`.

For anyone else who might have issues due to this, you can pass `--inverty` to un-nvert it. If the change is intended, I suggest to change `--inverty` to `--noinverty` to follow the pattern of other options.

**Comment by asarnow** [comment]
--inverty was broken for a while (wrong command line logic made the argument do nothing) so probably they had it when they didn't need it, then since it's fixed now and works, they have the unexpected result.

cryoSPARC inverts Relion coordinates on import for use with its own conventions. When we export for the same micrographs, the default case for a long time, we must invert this inversion. However if we export for flipped micrographs, because we changed motion correction program, then we need to keep the inverted values, with `--inverty`. The latter case is more common now because of using cryoSPARC Live and then going to Relion for Bayesian polishing.

Now you can always use disparticle.py to figure out the correct arguments for csparc2star.py.
