### ISSUE TITLE
bug generating the .star file with numpy==1.24.3

### ISSUE THREAD

**Issue by fonsecareyna82** [asarnow/pyem#105]
When try to generate a star file with a new installation of pyem, the process fail. There are functions that do not exist in this version, e.g. np.int. I think that the versions of the packages in the requirements.txt file must be updated

**Comment by clil16** [comment]
The reason is `np.int` (which is shorthand in the pyem code for the `numpy.int` alias) was deprecated in [numpy 1.20.0](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) and was removed in [numpy 1.24.0](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations)

If you downgrade numpy below 1.24.0 it will work, pyem still works with numpy 1.23.5.

`(pyem) $ conda install numpy=1.23.5`

The other option would be to replace all occurrences of the alias `np.int` with the builtin `int` since the alias pointed to the `int` builtin anyway.
