### ISSUE TITLE
csparc2star.py --copy-micrographs-coordinates

### ISSUE THREAD

**Issue by sunny1226** [asarnow/pyem#55]
There is a new bug while I export particles to cryosparc then export it back to relion using relion-3.1. 
When I export star file from relion, the OpticsGroup number is "1,2,3" and when I using csparc2star go back, it turns to "2,3,4" so that relion cannot reextract those particles. Now I just use vim to replace OpticsNumbers to the right one. Could we have a parameter fix it? Thanks!

**Comment by asarnow** [comment]
Thanks for reporting. CryoSPARC indexes it's own optics groups starting from 0, which caused Relion to emit a warning and modify the group numbers. Therefore, I had `csparc2star.py` add 1 during export. It seems cryoSPARC keeps the original numbers on import, though, leading to this issue.

I am not sure what is best, to add 1 and simplify the most common case, where one simply exports from cryoSPARC, or to keep the numbers as-is and warn the user to pay attention with Relion.

Do you have any thoughts? Some people will need to edit the file by hand either way...

**Comment by sunny1226** [comment]
In this way, I think this should depend on the parameter --copy-micrographs-coordinates. while using this parameter, people would like to re-import the data to relion. Or we could add a new parameter like --optics-origin so that we could chose add 1 or not. Would it help?

**Comment by asarnow** [comment]
The problem is that *Relion* always modified the group names / numbers, so we actually need something that operates post-facto on Relion outputs. It turns out I already added `--offset-optics <N>` to `star.py`, though. This will add N to the optics group numbers in a star file (N may be negative). This means you have to make another star file, but it does address the issue. Hope that helps!
