### ISSUE TITLE
exception raised when dealing with cryosparc 3.0.1's passsthrough_particle.cs

### ISSUE THREAD

**Issue by inter1965** [asarnow/pyem#59]
pyem-csparc2star XXXX_passthrough_particles.cs Stars/XXXXp.star
`
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
Required fields could not be mapped. Are you using the right input file(s)?
`

**Comment by blakely3dnm** [comment]
Hi and thanks for making this software. It has come in handy many times. 
I am seeing this problem as well, but only in one case since moving to CryoSPARC v3.  Currently, I am attempting to export from a NU-refinement (NEW) job type. If I include the passthrough particles, it gives the above-mentioned error. Leaving out the passthrough particles produces a .star file but it lacks the #rlnMicrographName column (which would be nice to have for Polishing). Taking a closer look at the passthrough output, it includes the expected `alignments3D` but also unexpectedly includes `alignments_class_0` , `alignments_class_1` ,and `alignments_class_2`. I'm assuming these were carried over from either the ab-initio job or heterogeneous refinement job I completed just prior to running NU-refinement. My other NU-refinement jobs do not have these extra alignments even though they are downstream of some 3D classification jobs. It seems odd to me that these alignments would be retained in cryoSPARC. Maybe this is related to the error?

**Comment by asarnow** [comment]
Possibly fixed by 4eb57bd, would appreciate it if you have the time to check.

**Comment by asarnow** [comment]
Believe this is now fixed thanks to @kttn8769 .
